apiVersion: v1
kind: Service
metadata:
  name:  sigo-discovery-server-service
  namespace: staging
spec:
  ports:
    - protocol: "TCP"
      port: 8761
      targetPort: 8761
  selector:
    app:  sigo-discovery-server
  type: LoadBalancer
  externalIPs:
  - 192.168.49.2