apiVersion: v1
kind: Service
metadata:
  name:  sigo-zuul-api-gateway-service
  namespace: staging
spec:
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  selector:
    app:  sigo-zuul-api-gateway
  type: LoadBalancer
  externalIPs:
  - 192.168.49.2