apiVersion: v1
kind: Service
metadata:
  name:  sigo-consultancy-microservice-service
  namespace: staging
spec:
  ports:
    - protocol: "TCP"
      port: 8004
      targetPort: 8004
  selector:
    app:  sigo-consultancy-microservice
  type: LoadBalancer
  externalIPs:
  - 192.168.49.2