apiVersion: v1
kind: Service
metadata:
  name:  sigo-app-service
  namespace: staging
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app:  sigo-app
  type: LoadBalancer
  externalIPs:
  - 192.168.49.2